name: Dummy Workflow
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4.0.0

      - name: Install deps
        run: pnpm install

      - name: Run dev server
        run: pnpm run dev

      - name: Run tests
        run: pnpm run test